<methodCall>
	<methodName>pingback.ping</methodName>
	<params>
		<param>
			<value><string>{$source}</string></value>
		</param>
		<param>
			<value><string>{$target}</string></value>
		</param>
	</params>
</methodCall>